package retCode

const (
	SUCCESS = 200

	// User Error
	ERROR_USER_EXIST = 3001 // 用户已存在
	ERROR_USER_CREATE = 3002 // 用户创建失败
	ERROR_USER_DELETE = 3003 // 用户删除失败
	ERROR_USER_QUERY = 3004 // 用户查询失败
	ERROR_USER_NOT_EXIST = 3005 // 查询用户不存在
	ERROR_USER_QUERY_ALL = 3006 // 用户分页查询失败
	ERROR_USER_UPDATE = 3007 // 用户修改失败
)

var retCodeMsg = map[int]string{
	SUCCESS: "SUCCESS",
	ERROR_USER_EXIST: "ERROR_USER_EXIST",
	ERROR_USER_CREATE: "ERROR_USER_CREATE",
	ERROR_USER_DELETE: "ERROR_USER_DELETE",
	ERROR_USER_QUERY: "ERROR_USER_QUERY",
	ERROR_USER_NOT_EXIST: "ERROR_USER_NOT_EXIST",
	ERROR_USER_QUERY_ALL: "ERROR_USER_QUERY_ALL",
	ERROR_USER_UPDATE: "ERROR_USER_UPDATE",
}

func GetRetCodeMsg(code int) string {
	return retCodeMsg[code]
}